IF Object_Id('Desk','U') IS NOT NULL
 SET NOEXEC ON
GO
CREATE TABLE [Desk]
(
    DeskId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    DeskNumber INT NOT NULL,
    RoomId UNIQUEIDENTIFIER,
    IsOccupied BIT NOT NULL,
    IsStatic BIT NOT NULL
) ON [PRIMARY]
SET NOEXEC OFF
