CREATE DATABASE test123
USE test123

CREATE TABLE [Dog]
(
	[id] UNIQUEIDENTIFIER PRIMARY KEY,
	[age] INT,
	[name] NVARCHAR(255) 
)

CREATE TABLE [Desk](
	[DeskId] UNIQUEIDENTIFIER PRIMARY KEY,
	[DeskNumber] INT,
	[RoomId] UNIQUEIDENTIFIER,
	[IsOccupied] BIT,
	[IsStatic] BIT
)

INSERT INTO Dog(id, age , name)
VALUES(NEWID(),10,'Brian')